apiVersion: v1
kind: Service
metadata:
  name: reactfrontend-service-production
  namespace: production
spec:
  selector:
    app: production
    type: frontend
  ports:
  - port: 5000
    targetPort: 5000
    NodePort: 30080

